import { useState, useRef, useEffect } from 'react'
import { uploadFile, sendChat, deleteDocument, resetDB } from './api'
import ReactMarkdown from 'react-markdown'
import './App.css'

const STEPS = [
  { id: 1, title: 'Document Loading',  desc: 'Extract text from PDF or Word file' },
  { id: 2, title: 'Text Chunking',     desc: 'Split into 500-char overlapping segments' },
  { id: 3, title: 'Embedding + Store', desc: 'sentence-transformers → ChromaDB' },
  { id: 4, title: 'Query Retrieval',   desc: 'Cosine similarity search top-5 chunks' },
  { id: 5, title: 'LLM Generation',    desc: 'Answer generated by selected model' },
]

const ACCEPTED = '.pdf,.docx'

function getFileIcon(filename = '') {
  return filename.toLowerCase().endsWith('.pdf') ? '📄' : '📝'
}
function getFileLabel(filename = '') {
  return filename.toLowerCase().endsWith('.pdf') ? 'PDF' : 'DOCX'
}
function getFileBadgeClass(filename = '') {
  return filename.toLowerCase().endsWith('.pdf') ? 'pdf' : 'word'
}

export default function App() {
  const [mode, setMode]             = useState('openai')   // 'openai' or 'local'
  const [apiKey, setApiKey]         = useState('')
  const [keyVisible, setKeyVisible] = useState(false)
  const [keyValid, setKeyValid]     = useState(false)

  const [documents, setDocuments]   = useState([])
  const [activeDocs, setActiveDocs] = useState('all')
  const [uploading, setUploading]   = useState(false)
  const [uploadPct, setUploadPct]   = useState(0)

  const [activeStep, setActiveStep] = useState(0)
  const [doneSteps, setDoneSteps]   = useState([])

  const [messages, setMessages]     = useState([])
  const [input, setInput]           = useState('')
  const [thinking, setThinking]     = useState(false)
  const [status, setStatus]         = useState('idle')
  const [dragOver, setDragOver]     = useState(false)

  const fileInputRef = useRef(null)
  const chatEndRef   = useRef(null)
  const textareaRef  = useRef(null)

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, thinking])

  const handleKeyChange = (val) => {
    setApiKey(val)
    // Gemini keys start with "AIza"
    setKeyValid(val.trim().startsWith('sk-') && val.trim().length > 20 && val.trim().length > 20)
  }

  const isReady = mode === 'local' ? true : keyValid

  const handleFile = async (file) => {
    if (!file) return
    const ext = file.name.split('.').pop().toLowerCase()
    if (!['pdf', 'docx'].includes(ext)) {
      return alert('Please upload a PDF (.pdf) or Word (.docx) file.')
    }
    if (!isReady) return alert('Please enter a valid  API key first.')

    setUploading(true)
    setDoneSteps([])
    setActiveStep(1)

    try {
      const stepDelay = (n, ms) =>
        new Promise(r => setTimeout(() => {
          setDoneSteps(prev => [...prev, n])
          setActiveStep(n + 1)
          r()
        }, ms))

      const uploadPromise = uploadFile(file, apiKey, (pct) => setUploadPct(pct))
      await stepDelay(1, 800)
      await stepDelay(2, 600)
      await stepDelay(3, 400)

      const stats = await uploadPromise
      setDoneSteps([1, 2, 3])
      setActiveStep(0)
      setDocuments(prev => {
        const filtered = prev.filter(d => d.doc_id !== stats.doc_id)
        return [...filtered, stats]
      })
      setActiveDocs('all')
      setStatus('ready')
    } catch (err) {
      alert('Upload failed: ' + (err.response?.data?.detail || err.message))
      setStatus(documents.length > 0 ? 'ready' : 'idle')
      setActiveStep(0)
    } finally {
      setUploading(false)
      if (fileInputRef.current) fileInputRef.current.value = ''
    }
  }

  const onDrop = (e) => {
    e.preventDefault()
    setDragOver(false)
    handleFile(e.dataTransfer.files[0])
  }

  const handleDelete = async (docId) => {
    try {
      await deleteDocument(docId)
      setDocuments(prev => prev.filter(d => d.doc_id !== docId))
      if (activeDocs === docId) setActiveDocs('all')
      if (documents.length <= 1) setStatus('idle')
    } catch (err) {
      alert('Delete failed: ' + (err.response?.data?.detail || err.message))
    }
  }

  const handleResetAll = async () => {
    await resetDB().catch(() => {})
    setDocuments([])
    setMessages([])
    setActiveDocs('all')
    setDoneSteps([])
    setActiveStep(0)
    setStatus('idle')
  }

  const handleSend = async () => {
    const q = input.trim()
    if (!q || thinking || documents.length === 0) return
    if (!isReady) return alert('Please enter a valid Gemini API key.')

    setMessages(prev => [...prev, { role: 'user', content: q }])
    setInput('')
    setThinking(true)
    setStatus('thinking')
    setActiveStep(4)

    const docId = activeDocs === 'all' ? null : activeDocs

    try {
      const res = await sendChat(q, mode, mode === 'openai' ? apiKey : '', docId)
      setDoneSteps(prev => [...prev, 4, 5])
      setActiveStep(0)
      setMessages(prev => [...prev, {
        role:     'ai',
        content:  res.answer,
        chunks:   res.chunks,
        searched: res.searched,
        mode:     res.mode,
      }])
      setStatus('ready')
    } catch (err) {
      setMessages(prev => [...prev, {
        role:    'ai',
        content: '⚠️ Error: ' + (err.response?.data?.detail || err.message),
        isError: true,
      }])
      setStatus('error')
      setActiveStep(0)
    } finally {
      setThinking(false)
    }
  }

  const handleInputChange = (e) => {
    setInput(e.target.value)
    e.target.style.height = 'auto'
    e.target.style.height = Math.min(e.target.scrollHeight, 120) + 'px'
  }

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend() }
  }

  const stepState = (id) => {
    if (doneSteps.includes(id)) return 'done'
    if (activeStep === id)      return 'active'
    return 'idle'
  }

  const hasDocuments = documents.length > 0

  return (
    <div className="app">

      {/* Topbar */}
      <header className="topbar">
        <div className="logo-icon">🧠</div>
        <span className="logo-text">Lexio<span>AI</span></span>
        <span className="topbar-tag">PDF · DOCX · RAG</span>
        <div className="topbar-right">
          <div className={`status-dot ${status === 'ready' ? 'ready' : status === 'thinking' ? 'thinking' : status === 'error' ? 'error' : ''}`} />
          <span className="status-label">
            {status === 'idle'     && 'no documents'}
            {status === 'ready'    && `${documents.length} doc${documents.length !== 1 ? 's' : ''} ready`}
            {status === 'thinking' && 'thinking…'}
            {status === 'error'    && 'error'}
          </span>
        </div>
      </header>

      {/* Sidebar */}
      <aside className="sidebar">

        {/* Mode Toggle */}
        <div className="sidebar-section">
          <div className="section-label">LLM Mode</div>
          <div className="mode-toggle">
            <button
              className={`mode-btn ${mode === 'openai' ? 'active' : ''}`}
              onClick={() => setMode('openai')}
            >
              🤖 OpenAI
            </button>
            <button
              className={`mode-btn ${mode === 'local' ? 'active' : ''}`}
              onClick={() => setMode('local')}
            >
              💻 Local (Ollama)
            </button>
          </div>

          {/* Gemini API Key */}
          {mode === 'openai' && (
            <div style={{ marginTop: 12 }}>
              <div className={`key-input-wrap ${keyValid ? 'valid' : ''}`}>
                <span className="key-icon">🔑</span>
                <input
                  type={keyVisible ? 'text' : 'password'}
                  className="key-input"
                  placeholder="sk-••••••••••••••••••••"
                  value={apiKey}
                  onChange={e => handleKeyChange(e.target.value)}
                />
                <button className="key-toggle" onClick={() => setKeyVisible(v => !v)}>
                  {keyVisible ? '🙈' : '👁️'}
                </button>
              </div>
              {keyValid
                ? <div className="key-status valid">✓ OpenAI key looks valid</div>
                : <div className="key-status">Get free key at <a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">platform.openai.com/api-keys</a></div>
              }
            </div>
          )}

          {/* Ollama info */}
          {mode === 'local' && (
            <div className="ollama-info">
              <div className="ollama-dot"></div>
              <div>
                <div className="ollama-title">llama3.2 · running locally</div>
                <div className="ollama-sub">Make sure <code>ollama serve</code> is running</div>
              </div>
            </div>
          )}
        </div>

        {/* Upload */}
        <div className="sidebar-section">
          <div className="section-label-row">
            <span className="section-label" style={{marginBottom:0}}>Documents</span>
            {hasDocuments && <button className="reset-all-btn" onClick={handleResetAll}>Clear all</button>}
          </div>

          <div
            className={`drop-zone ${uploading ? 'processing' : ''} ${dragOver ? 'dragover' : ''}`}
            style={{ marginTop: 10 }}
            onDrop={onDrop}
            onDragOver={e => { e.preventDefault(); setDragOver(true) }}
            onDragLeave={() => setDragOver(false)}
            onClick={() => !uploading && fileInputRef.current?.click()}
          >
            <input
              ref={fileInputRef}
              type="file"
              accept={ACCEPTED}
              style={{ display: 'none' }}
              onChange={e => handleFile(e.target.files[0])}
            />
            {uploading ? (
              <>
                <div className="drop-icon">⚙️</div>
                <div className="drop-title">Processing document…</div>
                <div className="progress-track">
                  <div className="progress-fill" style={{ width: uploadPct + '%' }} />
                </div>
                <div className="drop-sub">{uploadPct}% uploaded</div>
              </>
            ) : (
              <>
                <div className="drop-icon">{hasDocuments ? '➕' : '📂'}</div>
                <div className="drop-title">{hasDocuments ? 'Add another document' : 'Drop document here'}</div>
                <div className="file-type-badges">
                  <span className="ftype-badge pdf">PDF</span>
                  <span className="ftype-badge word">DOCX</span>
                </div>
              </>
            )}
          </div>

          {hasDocuments && (
            <div className="doc-list">
              <div
                className={`doc-item ${activeDocs === 'all' ? 'active' : ''}`}
                onClick={() => setActiveDocs('all')}
              >
                <span className="doc-item-icon">🗂️</span>
                <div className="doc-item-meta">
                  <div className="doc-item-name">All Documents</div>
                  <div className="doc-item-sub">{documents.length} files · search everything</div>
                </div>
              </div>
              {documents.map(doc => (
                <div
                  key={doc.doc_id}
                  className={`doc-item ${activeDocs === doc.doc_id ? 'active' : ''}`}
                  onClick={() => setActiveDocs(doc.doc_id)}
                >
                  <span className="doc-item-icon">{getFileIcon(doc.filename)}</span>
                  <div className="doc-item-meta">
                    <div className="doc-item-name" title={doc.filename}>{doc.filename}</div>
                    <div className="doc-item-sub">
                      <span className={`ftype-pill ${getFileBadgeClass(doc.filename)}`}>
                        {getFileLabel(doc.filename)}
                      </span>
                      {doc.pages}p · {doc.chunks} chunks
                    </div>
                  </div>
                  <button
                    className="doc-delete-btn"
                    onClick={e => { e.stopPropagation(); handleDelete(doc.doc_id) }}
                    title="Remove"
                  >×</button>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Pipeline */}
        <div className="pipeline-section">
          <div className="section-label">RAG Pipeline</div>
          {STEPS.map(step => (
            <div key={step.id} className={`pipeline-step ${stepState(step.id)}`}>
              <div className="step-dot">
                {stepState(step.id) === 'done'  && '✓'}
                {stepState(step.id) === 'active' && '…'}
                {stepState(step.id) === 'idle'   && step.id}
              </div>
              <div>
                <div className="step-title">{step.title}</div>
                <div className="step-desc">{step.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </aside>

      {/* Chat */}
      <main className="chat-main">
        <div className="chat-messages">

          {messages.length === 0 && !thinking && (
            <div className="welcome">
              <div className="welcome-icon">🧠</div>
              <div className="welcome-title">
                {hasDocuments
                  ? activeDocs === 'all'
                    ? `Searching across ${documents.length} document${documents.length !== 1 ? 's' : ''}`
                    : `Chatting with "${documents.find(d => d.doc_id === activeDocs)?.filename}"`
                  : 'Upload a document to start'}
              </div>
              <div className="welcome-sub">
                {hasDocuments
                  ? `Using ${mode === 'openai' ? 'OpenAI (gpt-4o-mini)' : 'Ollama (llama3.2 local)'} to answer.`
                  : 'Choose your LLM mode, then upload a PDF or Word document.'}
              </div>
              {!hasDocuments && (
                <div className="file-type-grid">
                  <div className="ftype-card">
                    <span>📄</span>
                    <strong>PDF</strong>
                    <p>Reports, manuals, research papers</p>
                  </div>
                  <div className="ftype-card">
                    <span>📝</span>
                    <strong>Word (.docx)</strong>
                    <p>Documents, letters, proposals</p>
                  </div>
                </div>
              )}
              {hasDocuments && (
                <div className="example-chips">
                  {['Summarize the main topics', 'What are the key findings?', 'List the important points'].map(q => (
                    <button key={q} className="chip" onClick={() => { setInput(q); textareaRef.current?.focus() }}>
                      → {q}
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}

          {messages.map((msg, i) => (
            <div key={i} className={`msg ${msg.role}`}>
              <div className="msg-role">
                {msg.role === 'user' ? 'You' : 'Lexio AI'}
                {msg.searched && msg.role === 'ai' && (
                  <span className="searched-tag">
                    {msg.searched === 'all'
                      ? '🗂️ all documents'
                      : `${getFileIcon(documents.find(d => d.doc_id === msg.searched)?.filename || '')} ${documents.find(d => d.doc_id === msg.searched)?.filename || msg.searched}`}
                  </span>
                )}
                {msg.mode && msg.role === 'ai' && (
                  <span className={`mode-tag ${msg.mode}`}>
                    {msg.mode === 'openai' ? '🤖 OpenAI' : '💻 Ollama'}
                  </span>
                )}
              </div>
              <div className={`msg-bubble ${msg.isError ? 'error' : ''}`}>
                {msg.role === 'ai'
                  ? <ReactMarkdown>{msg.content}</ReactMarkdown>
                  : <p>{msg.content}</p>
                }
              </div>
              {msg.chunks?.length > 0 && (
                <div className="source-row">
                  {msg.chunks.map((c, ci) => (
                    <span key={ci} className="source-badge">
                      {getFileIcon(c.filename)} {c.filename.replace(/\.[^/.]+$/, '')} · #{c.chunk_index}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}

          {thinking && (
            <div className="msg ai">
              <div className="msg-role">
                Lexio AI
                <span className={`mode-tag ${mode}`}>
                  {mode === 'openai' ? '🤖 OpenAI' : '💻 Ollama'}
                </span>
              </div>
              <div className="msg-bubble thinking">
                <span className="dot" /><span className="dot" /><span className="dot" />
              </div>
            </div>
          )}

          <div ref={chatEndRef} />
        </div>

        {hasDocuments && (
          <div className="scope-bar">
            <span className="scope-label">Searching:</span>
            <button className={`scope-btn ${activeDocs === 'all' ? 'active' : ''}`} onClick={() => setActiveDocs('all')}>
              🗂️ All docs
            </button>
            {documents.map(doc => (
              <button
                key={doc.doc_id}
                className={`scope-btn ${activeDocs === doc.doc_id ? 'active' : ''}`}
                onClick={() => setActiveDocs(doc.doc_id)}
              >
                {getFileIcon(doc.filename)} {doc.filename.length > 18 ? doc.filename.slice(0, 18) + '…' : doc.filename.replace(/\.[^/.]+$/, '')}
              </button>
            ))}
          </div>
        )}

        <div className="input-area">
          <div className={`input-wrap ${!hasDocuments ? 'disabled' : ''}`}>
            <textarea
              ref={textareaRef}
              className="chat-input"
              rows={1}
              value={input}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              placeholder={hasDocuments ? `Ask anything… (${mode === 'openai' ? 'OpenAI API' : 'Ollama local'})` : 'Upload a document first…'}
              disabled={!hasDocuments || thinking}
            />
            <button
              className="send-btn"
              onClick={handleSend}
              disabled={!hasDocuments || thinking || !input.trim()}
            >➤</button>
          </div>
          <div className="input-hint">Enter to send · Shift+Enter for newline</div>
        </div>
      </main>
    </div>
  )
}